[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid
loglevel=info

[program:uvicorn]
command=uvicorn backend.app.main:app --host 0.0.0.0 --port 7860
directory=/app
user=root

autostart=true
autorestart=true

stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

environment=PYTHONPATH="/app/backend",DATABASE_URL="%(ENV_DATABASE_URL)s",SECRET_KEY="%(ENV_SECRET_KEY)s"

[program:redis]
command=redis-server --port 6379 --bind 127.0.0.1

autostart=true
autorestart=true

stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock